package com.ManifestTeswTancis.RabbitConfigurations;

public interface MessageNames {
    String CUSTOMS_VESSEL_REFERENCE ="CUSTOMS_VESSEL_REFERENCE";
    String CUSTOM_CLEARANCE_NOTICE ="CUSTOM_CLEARANCE_NOTICE";
    String CUSTOM_CLEARANCE_STATUS ="CUSTOM_CLEARANCE_STATUS";
    String MANIFEST_APPROVAL_NOTICE ="MANIFEST_APPROVAL_NOTICE";
    String SUBMITTED_MANIFEST_STATUS ="SUBMITTED_MANIFEST_STATUS";
    String MANIFEST_AMENDMENT_NOTICE ="MANIFEST_AMENDMENT_NOTICE";
    String MANIFEST_AMENDMENT_STATUS ="MANIFEST_AMENDMENT_STATUS";
    String TESWS_BILL_NOTICE ="TESWS_BILL_NOTICE";
    String TESWS_PAYMENT_NOTICE ="TESWS_PAYMENT_NOTICE";
    String EXPORT_MANIFEST_APPROVAL_NOTICE="EXPORT_MANIFEST_APPROVAL_NOTICE";
    String SUBMITTED_EXPORT_MANIFEST_STATUS="SUBMITTED_EXPORT_MANIFEST_STATUS";
    String CUSTOMS_VESSEL_REFERENCE_RESEND ="CUSTOMS_VESSEL_REFERENCE_RESEND";
}
