package com.ManifestTeswTancis.RabbitConfigurations;

public interface MessageNames {
    String CUSTOMS_VESSEL_REFERENCE ="CUSTOMS_VESSEL_REFERENCE";
    String CUSTOM_CLEARANCE_NOTICE ="CUSTOM_CLEARANCE_NOTICE";
    String CUSTOM_CLEARANCE_STATUS ="CUSTOM_CLEARANCE_STATUS";
    String MANIFEST_APPROVAL_NOTICE ="MANIFEST_APPROVAL_NOTICE";
    String SUBMITTED_MANIFEST_STATUS ="SUBMITTED_MANIFEST_STATUS";
    String MANIFEST_AMENDMENT_NOTICE ="MANIFEST_AMENDMENT_NOTICE";
    String MANIFEST_AMENDMENT_STATUS ="MANIFEST_AMENDMENT_STATUS";
}
